services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: baseTaller
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always

  s-personas:
    build: ./s-personas
    ports:
      - "9081:9081"  # Ajusta según el puerto configurado en server.xml
    depends_on:
      - db
    restart: always

  s-recursos:
    build: ./s-recursos
    ports:
      - "9082:9082"  # Ajusta según el puerto configurado en server.xml
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
